// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxbriipvpwgkpcztnend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94YnJpaXB2cHdna3BjenRuZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTgyMzMsImV4cCI6MjA2MzE3NDIzM30.J_g2uA2pkCGz8Mykk7hC0ed1qcHgjs-Luova-mJ5FnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);